name: QuestPlugin
version: 1.0
main: com.example.questplugin.QuestPlugin
api-version: 1.20
commands:
  questdev:
    description: Developer tools for testing quests
    permission: questplugin.dev
    usage: /<command>
  questreload:
    description: Reloads the config and quest templates
    permission: questplugin.admin
    usage: /<command>
permissions:
  questplugin.dev:
    description: Allows access to developer commands
    default: op
  questplugin.admin:
    description: Allows reloading and admin-level commands
    default: op
