name: QuestPlugin
version: 1.1
main: com.example.questplugin.QuestPlugin
api-version: 1.20
author : auradev
depend: [UniversalScoreboard]
softdepend:
  - Vault
  - PlaceholderAPI
  - Citizens
  - AuraSkills
commands:
  questdev:
    description: Development tools for testing
    permission: questplugin.dev
    usage: /<command> [reloadtemplates|forcecomplete|simreset|dumpcache]
  
  questadmin:
    description: Administrative quest controls
    permission: questplugin.admin
    usage: /<command> [resetglobal|playerstats|reloadconfig|migrate]

  quest:
    description: Opens your quest menu
    usage: /quest
    permission: questplugin.use
    
permissions:
  questplugin.dev:
    description: Access to development tools
    default: op
  questplugin.admin:
    description: Administrative quest controls
    default: op
